const data = {
    products: [
        {
            name: 'North Shore Oak Vinyl Longboards Flooring',
            slug: 'North Shore Oak Vinyl Longboards Flooring',
            category: 'Vinyl Plank Flooring',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'CALI',
            rating: 4.5,
            numReviews: 10,
            description: '100% Waterproof and easy to clean, Easy-to-install lightweight planks. Features a rapid click-lock groove system',
        },
        {
            name: 'Reefwood Vinyl Longboards Flooring',
            slug: 'Reefwood Vinyl Longboards Flooring',
            category: 'Vinyl Plank Flooring',
            image: '/images/p2.jpg',
            price: 250,
            countInStock: 20,
            brand: 'CALI',
            rating: 4.0,
            numReviews: 10,
            description: '100% Waterproof and easy to clean, Easy-to-install lightweight planks. Features a rapid click-lock groove system',
        },
        {
            name: 'Oceanic Oak Vinyl Longboards Flooring',
            slug: 'Oceanic Oak Vinyl Longboards Flooring',
            category: 'Vinyl Plank Flooring',
            image: '/images/p3.jpg',
            price: 25,
            countInStock: 15,
            brand: 'CALI',
            rating: 4.5,
            numReviews: 14,
            description: '100% Waterproof and easy to clean, Easy-to-install lightweight planks. Features a rapid click-lock groove system',
        },
        {
            name: 'Sandbar Oak Vinyl Longboards Flooring',
            slug: 'Sandbar Oak Vinyl Longboards Flooring',
            category: 'Vinyl Plank Flooring',
            image: '/images/p4.jpg',
            price: 65,
            countInStock: 5,
            brand: 'CALI',
            rating: 4.5,
            numReviews: 10,
            description: '100% Waterproof and easy to clean, Easy-to-install lightweight planks. Features a rapid click-lock groove system',
        },
    ],
};
export default data;
